### ISSUE TITLE
Improve performance of roll command

### ISSUE THREAD

**Issue by EdmundGoodman** [UWCS/apollo#237]
The roll command is very inefficient for large inputs (for example `(500d2)d1000`). It should be re-worked to improve the stability of the Apollo bot.

**Comment by Jlobblet** [comment]
When running a large roll command, the whole bot hangs. It's not so much an "inefficient" thing as a "too much work to do feasibly" thing. The bot locks up because currrently the roll work is being done on a separate thread, rather than a process, so it gets stuck with the GIL.

Using a process instead would stop Apollo from hanging (I've tested this) but still runs into the issue of consuming system resources by performing a large comptuation, which doesn't terminate quickly.

Using a future for the work and raising the `reduce` methods to `async` would introduce coroutine points for the dice roll evaluator to be interrupted by something like `asyncio.wait_for`, but it isn't trivial. Without anything *actually* asynchronous, the program never has anywhere to actually yield control and have the `CancelledError` to be raised by the loop. Since the code inside the `reduce` tree is all synchronous, it would have to be modified manually to support this.

It may be easiest to instead create a subprocess to run the work and manually kill it after some duration rather than trying to modify the evaluation code to support this. I'll investigate this now.
